# base theme (light, dark, intellij, darcula, maclight or macdark); only used by theme editor
@baseTheme=dark
@background=#09090b
@foreground=#EDEDED
@accentColor=#EDEDED
Button.background=#1A1A1A
Button.borderColor=#2E2E2E
Button.hoverBackground=#1F1F1F
Button.hoverBorderColor=#454545
Button.focusedBackground=#292929
Button.focusedBorderColor=#878787
ToggleButton.background=#1A1A1A
ToggleButton.borderColor=#2E2E2E
ToggleButton.hoverBackground=#1F1F1F
ToggleButton.hoverBorderColor=#454545
ToggleButton.focusedBackground=#292929
ToggleButton.focusedBorderColor=#878787
CheckBox.background=#1A1A1A
CheckBox.borderColor=#2E2E2E
CheckBox.hoverBackground=#1F1F1F
CheckBox.hoverBorderColor=#454545
CheckBox.focusedBackground=#292929
CheckBox.focusedBorderColor=#878787
RadioButton.background=#1A1A1A
RadioButton.borderColor=#2E2E2E
RadioButton.hoverBackground=#1F1F1F
RadioButton.hoverBorderColor=#454545
RadioButton.focusedBackground=#292929
RadioButton.focusedBorderColor=#878787
ComboBox.background=#09090b
ComboBox.borderColor=#2E2E2E
ComboBox.hoverBackground=#09090b
ComboBox.hoverBorderColor=#454545
ComboBox.focusedBackground=#09090b
ComboBox.focusedBorderColor=#878787
Spinner.background=#1A1A1A
Spinner.borderColor=#2E2E2E
Spinner.hoverBackground=#1F1F1F
Spinner.hoverBorderColor=#454545
Spinner.focusedBackground=#292929
Spinner.focusedBorderColor=#878787
TextField.background=#1A1A1A
TextField.borderColor=#2E2E2E
TextField.hoverBackground=#1F1F1F
TextField.hoverBorderColor=#454545
TextField.focusedBackground=#292929
TextField.focusedBorderColor=#878787
FormattedTextField.background=#1A1A1A
FormattedTextField.borderColor=#2E2E2E
FormattedTextField.hoverBackground=#1F1F1F
FormattedTextField.hoverBorderColor=#454545
FormattedTextField.focusedBackground=#292929
FormattedTextField.focusedBorderColor=#878787
PasswordField.background=#1A1A1A
PasswordField.borderColor=#2E2E2E
PasswordField.hoverBackground=#1F1F1F
PasswordField.hoverBorderColor=#454545
PasswordField.focusedBackground=#292929
PasswordField.focusedBorderColor=#878787
TextArea.background=#1A1A1A
TextArea.borderColor=#2E2E2E
TextArea.hoverBackground=#1F1F1F
TextArea.hoverBorderColor=#454545
TextArea.focusedBackground=#292929
TextArea.focusedBorderColor=#878787
EditorPane.background=#1A1A1A
EditorPane.borderColor=#2E2E2E
EditorPane.hoverBackground=#1F1F1F
EditorPane.hoverBorderColor=#454545
EditorPane.focusedBackground=#292929
EditorPane.focusedBorderColor=#878787
TextPane.background=#1A1A1A
TextPane.borderColor=#2E2E2E
TextPane.hoverBackground=#1F1F1F
TextPane.hoverBorderColor=#454545
TextPane.focusedBackground=#292929
TextPane.focusedBorderColor=#878787
ScrollBar.background=#1A1A1A
ScrollBar.borderColor=#2E2E2E
ScrollBar.hoverBackground=#1F1F1F
ScrollBar.hoverBorderColor=#454545
ScrollBar.focusedBackground=#292929
ScrollBar.focusedBorderColor=#878787
Separator.background=#1A1A1A
Separator.borderColor=#2E2E2E
Separator.hoverBackground=#1F1F1F
Separator.hoverBorderColor=#454545
Separator.focusedBackground=#292929
Separator.focusedBorderColor=#878787
Slider.background=#1A1A1A
Slider.borderColor=#2E2E2E
Slider.hoverBackground=#1F1F1F
Slider.hoverBorderColor=#454545
Slider.focusedBackground=#292929
Slider.focusedBorderColor=#878787
ProgressBar.background=#1A1A1A
ProgressBar.borderColor=#2E2E2E
ProgressBar.hoverBackground=#1F1F1F
ProgressBar.hoverBorderColor=#454545
ProgressBar.focusedBackground=#292929
ProgressBar.focusedBorderColor=#878787
ToolTip.background=#1A1A1A
ToolTip.borderColor=#2E2E2E
ToolTip.hoverBackground=#1F1F1F
ToolTip.hoverBorderColor=#454545
ToolTip.focusedBackground=#292929
ToolTip.focusedBorderColor=#878787
List.background=#0A0A0A
List.borderColor=#2E2E2E
List.hoverBackground=#1F1F1F
List.hoverBorderColor=#454545
List.focusedBackground=#292929
List.focusedBorderColor=#878787
Tree.background=#0A0A0A
Tree.borderColor=#2E2E2E
Tree.hoverBackground=#1F1F1F
Tree.hoverBorderColor=#454545
Tree.focusedBackground=#292929
Tree.focusedBorderColor=#878787
SplitPane.background=#1A1A1A
SplitPane.borderColor=#2E2E2E
SplitPane.hoverBackground=#1F1F1F
SplitPane.hoverBorderColor=#454545
SplitPane.focusedBackground=#292929
SplitPane.focusedBorderColor=#878787